### ISSUE TITLE
Error about blastn

### ISSUE THREAD

**Issue by Songq-20** [linxingchen/cobra#24]
Hi Dr Chen：
I try to run COBRA today with 
```Shell
source activate cobra
cobra-meta -f Megahit_out/611PES1/611PES1_megahit.contigs.fa -q checkv_in/611RW.fa -o COBRA/611_RW_MV_COBRA -c coverage/611RW_coverage.txt -m mapping/611RW-MV.sam -a megahit -mink 21 -maxk 141
conda deactivate
```
 and it works at beginning.
But it stop at cobra.py, line 1531:`r = open('blastdb_2.vs.blastdb_1', 'r')`
The error is 
```
makeblastdb: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
blastn: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data01nfs/user/songq/anaconda3/envs/cobra/bin/cobra-meta", line 10, in <module>
    sys.exit(main())
  File "/data01nfs/user/songq/anaconda3/envs/cobra/lib/python3.8/site-packages/cobra.py", line 1531, in main
    r = open('blastdb_2.vs.blastdb_1', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'blastdb_2.vs.blastdb_1'
```
`blastdb_1.fa` and `blastdb_2.fa` are written and not empty, and I also install BLAST in cobra env, so I guess The error was not caused by BLAST.
Please help me solve this problem, I am willing to provide you with any other information you need.
Thanks

**Comment by linxingchen** [comment]
Hi, thanks for reporting this issue. 

Did you have the same issue while running other samples?

**Comment by linxingchen** [comment]
Hi, thank you for your interest in COBRA.

This is probably not an error, because COBRA did not extend any contig/scaffold, thus there is nothing to compare with BLASTn. It would be great if you could share the debug file and the log file.
